import {Document, model, Schema} from 'mongoose';

export interface IChargeState extends Document {
  battery_heater_on: Boolean,
  battery_level: Number,
  battery_range: Number,
  charge_current_request: Number,
  charge_current_request_max: Number,
  charge_enable_request: Boolean,
  charge_energy_added: Number,
  charge_limit_soc: Number,
  charge_limit_soc_max: Number,
  charge_limit_soc_min: Number,
  charge_limit_soc_std: Number,
  charge_miles_added_ideal: Number,
  charge_miles_added_rated: Number,
  charge_port_cold_weather_mode: Boolean,
  charge_port_door_open: Boolean,
  charge_port_latch: String,
  charge_rate: Number,
  charge_to_max_range: Boolean,
  charger_actual_current: Number,
  // charger_phases: null,
  charger_pilot_current: Number,
  charger_power: Number,
  charger_voltage: Number,
  charging_state: String,
  conn_charge_cable: String,
  est_battery_range: Number,
  fast_charger_brand: String,
  fast_charger_present: Boolean,
  fast_charger_type: String,
  ideal_battery_range: Number,
  managed_charging_active: Boolean,
  // managed_charging_start_time: null,
  managed_charging_user_canceled: Boolean,
  max_range_charge_counter: Number,
  // not_enough_power_to_heat: null,
  scheduled_charging_pending: Boolean,
  // scheduled_charging_start_time: null,
  time_to_full_charge: Number,
  timestamp: Number,
  trip_charging: Boolean,
  usable_battery_level: Number
  // user_charge_enable_request: null
}


const ChargeStateSchema: Schema = new Schema({
  battery_heater_on: {type: Boolean},
  battery_level: {type: Number},
  battery_range: {type: Number},
  charge_current_request: {type: Number},
  charge_current_request_max: {type: Number},
  charge_enable_request: {type: Boolean},
  charge_energy_added: {type: Number},
  charge_limit_soc: {type: Number},
  charge_limit_soc_max: {type: Number},
  charge_limit_soc_min: {type: Number},
  charge_limit_soc_std: {type: Number},
  charge_miles_added_ideal: {type: Number},
  charge_miles_added_rated: {type: Number},
  charge_port_cold_weather_mode: {type: Boolean},
  charge_port_door_open: {type: Boolean},
  charge_port_latch: {type: String},
  charge_rate: {type: Number},
  charge_to_max_range: {type: Boolean},
  charger_actual_current: {type: Number},
// charger_phases: {type: null},
  charger_pilot_current: {type: Number},
  charger_power: {type: Number},
  charger_voltage: {type: Number},
  charging_state: {type: String},
  conn_charge_cable: {type: String},
  est_battery_range: {type: Number},
  fast_charger_brand: {type: String},
  fast_charger_present: {type: Boolean},
  fast_charger_type: {type: String},
  ideal_battery_range: {type: Number},
  managed_charging_active: {type: Boolean},
// managed_charging_start_time: {type: null},
  managed_charging_user_canceled: {type: Boolean},
  max_range_charge_counter: {type: Number},
// not_enough_power_to_heat: {type: null},
  scheduled_charging_pending: {type: Boolean},
// scheduled_charging_start_time: {type: null},
  time_to_full_charge: {type: Number},
  timestamp: {type: Number},
  trip_charging: {type: Boolean},
  usable_battery_level: {type: Number}

});

export default model('ChargeState', ChargeStateSchema);

